import { useFocusEffect } from 'expo-router';
import { ChevronLeft, ChevronRight, Plus, UsersRound } from 'lucide-react-native';
import { useCallback, useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, View } from 'react-native';

import { addTeamMember, getTeam, updateTeamMember } from '../../../src/api/client';
import { AppText } from '../../../src/components/AppText';
import { ActionButton, FormField, MorePage, SelectRow } from '../../../src/features/more/ui';
import { useAppTheme } from '../../../src/theme';
import type { TeamMember, TeamPage } from '../../../src/types/more';

export default function TeamScreen(){
  const theme=useAppTheme();const [data,setData]=useState<TeamPage|null>(null);const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [adding,setAdding]=useState(false);const [phone,setPhone]=useState('');const [role,setRole]=useState<'owner'|'collaborator'>('collaborator');const [money,setMoney]=useState(false);const [editing,setEditing]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{setData(await getTeam(page));setError(null);}catch(caught){setError(caught instanceof Error?caught.message:'Chargement impossible.');}finally{setLoading(false);}},[page]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  async function add(){setBusy(true);setError(null);try{await addTeamMember({phone,role,canViewMoney:money});setAdding(false);setPhone('');setRole('collaborator');setMoney(false);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Ajout impossible.');}finally{setBusy(false);}}
  async function update(member:TeamMember,changes:Partial<{role:'owner'|'collaborator';status:'active'|'disabled';canViewMoney:boolean}>){setBusy(true);setError(null);try{await updateTeamMember(member.membership_id,{role:changes.role??member.role,status:changes.status??(member.status==='active'?'active':'disabled'),canViewMoney:changes.canViewMoney??member.can_view_money});setEditing(null);await load();}catch(caught){setError(caught instanceof Error?caught.message:'Modification impossible.');}finally{setBusy(false);}}
  function confirmStatus(member:TeamMember){const active=member.status==='active';Alert.alert(active?'Désactiver ce membre ?':'Réactiver ce membre ?',active?'Il ne pourra plus accéder à cet atelier.':'Il retrouvera son accès à l’atelier.',[{text:'Retour',style:'cancel'},{text:'Confirmer',style:active?'destructive':'default',onPress:()=>void update(member,{status:active?'disabled':'active'})}]);}
  return <MorePage error={error} loading={loading&&!data} title="Équipe">
    {data?<><View style={[styles.summary,{borderColor:theme.colors.border}]}><UsersRound color={theme.colors.primary} size={22}/><View><AppText variant="label">{data.stats.active} membre{data.stats.active>1?'s':''} actif{data.stats.active>1?'s':''}</AppText><AppText color={theme.colors.textMuted} variant="caption">{data.planUsage.planLabel??'Offre actuelle'} · {data.planUsage.memberLimit===null?'Places illimitées':`${data.planUsage.activeMembers}/${data.planUsage.memberLimit} places utilisées`}</AppText></View></View>
      {adding?<View style={styles.form}><AppText variant="title3">Ajouter un membre</AppText><FormField keyboardType="phone-pad" label="Téléphone d’un compte Filéo existant" onChangeText={setPhone} value={phone}/><AppText color={theme.colors.textMuted} variant="caption">Rôle</AppText><SelectRow label="Collaborateur" onPress={()=>setRole('collaborator')} selected={role==='collaborator'}/><SelectRow label="Responsable" onPress={()=>setRole('owner')} selected={role==='owner'}/>{role==='collaborator'?<SwitchRow label="Accès financier" value={money} onChange={setMoney}/>:null}<ActionButton disabled={phone.trim().length<6||data.planUsage.limitReached} label="Ajouter à l’équipe" loading={busy} onPress={()=>void add()}/><ActionButton label="Fermer" onPress={()=>setAdding(false)} secondary/></View>:<Pressable accessibilityRole="button" disabled={data.planUsage.limitReached} onPress={()=>setAdding(true)} style={[styles.add,{borderColor:theme.colors.primary,opacity:data.planUsage.limitReached?.5:1}]}><Plus color={theme.colors.primary} size={19}/><AppText color={theme.colors.primary} variant="label">Ajouter un membre</AppText></Pressable>}
      {data.planUsage.limitReached?<AppText color={theme.colors.secondary} variant="caption">La limite de membres de votre offre est atteinte.</AppText>:null}
      <AppText variant="title3">Membres</AppText>
      {data.members.map((member)=><View key={member.membership_id} style={[styles.member,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Pressable onPress={()=>setEditing(editing===member.membership_id?null:member.membership_id)} style={styles.memberHeader}><View style={{flex:1,minWidth:0}}><AppText numberOfLines={1} variant="label">{member.full_name}</AppText><AppText color={theme.colors.textMuted} numberOfLines={1} variant="caption">{member.phone_e164} · {member.role==='owner'?'Responsable':'Collaborateur'}</AppText><AppText color={member.status==='active'?theme.colors.accent:theme.colors.secondary} variant="caption">{member.status==='active'?'Actif':'Désactivé'} · {member.assigned_items} article{member.assigned_items>1?'s':''} assigné{member.assigned_items>1?'s':''}</AppText></View><ChevronRight color={theme.colors.textSubtle} size={18}/></Pressable>{editing===member.membership_id?<MemberEditor busy={busy} member={member} onStatus={()=>confirmStatus(member)} onUpdate={(changes)=>void update(member,changes)}/>:null}</View>)}
      {data.pageCount>1?<View style={styles.pagination}><Pressable accessibilityLabel="Page précédente" disabled={page<=1} onPress={()=>setPage(page-1)}><ChevronLeft color={page<=1?theme.colors.textSubtle:theme.colors.primary} size={24}/></Pressable><AppText variant="caption">{data.page} / {data.pageCount}</AppText><Pressable accessibilityLabel="Page suivante" disabled={page>=data.pageCount} onPress={()=>setPage(page+1)}><ChevronRight color={page>=data.pageCount?theme.colors.textSubtle:theme.colors.primary} size={24}/></Pressable></View>:null}
    </>:null}
  </MorePage>;
}

function MemberEditor({member,busy,onUpdate,onStatus}:{member:TeamMember;busy:boolean;onUpdate:(changes:{role:'owner'|'collaborator';canViewMoney:boolean})=>void;onStatus:()=>void}){const theme=useAppTheme();const [role,setRole]=useState(member.role);const [money,setMoney]=useState(member.can_view_money);return <View style={[styles.form,{borderTopColor:theme.colors.border,borderTopWidth:1,paddingTop:12}]}><SelectRow label="Collaborateur" onPress={()=>setRole('collaborator')} selected={role==='collaborator'}/><SelectRow label="Responsable" onPress={()=>setRole('owner')} selected={role==='owner'}/>{role==='collaborator'?<SwitchRow label="Accès financier" onChange={setMoney} value={money}/>:null}<ActionButton label="Enregistrer les accès" loading={busy} onPress={()=>onUpdate({role,canViewMoney:role==='owner'||money})}/><ActionButton label={member.status==='active'?'Désactiver ce membre':'Réactiver ce membre'} onPress={onStatus} secondary/></View>;}

function SwitchRow({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){const theme=useAppTheme();return <View style={[styles.switchRow,{borderColor:theme.colors.border}]}><AppText style={{flex:1}} variant="label">{label}</AppText><Switch accessibilityLabel={label} onValueChange={onChange} value={value}/></View>;}

const styles=StyleSheet.create({summary:{alignItems:'center',borderBottomWidth:1,flexDirection:'row',gap:12,paddingBottom:16},add:{alignItems:'center',borderRadius:8,borderWidth:1,flexDirection:'row',gap:9,justifyContent:'center',minHeight:48},form:{gap:10},member:{borderRadius:8,borderWidth:1,padding:14},memberHeader:{alignItems:'center',flexDirection:'row',gap:10,minHeight:52},switchRow:{alignItems:'center',borderRadius:8,borderWidth:1,flexDirection:'row',minHeight:54,paddingHorizontal:13},pagination:{alignItems:'center',flexDirection:'row',gap:20,justifyContent:'center',padding:12}});
