import "server-only";
import {randomUUID} from "node:crypto";
import {recordAudit} from "@/lib/audit";
import {money,type CurrencyCode,type Money} from "@/lib/money";
import {sql,sqlOne,withPgTransaction,type PgExecutor} from "@/lib/supabase/postgres";
export type AdminCounts={workshops:number;activeWorkshops:number;trials:number;payingWorkshops:number;expiringSoon:number;openTickets:number;pendingPayments:number};
export async function getAdminCounts():Promise<AdminCounts>{return(await sqlOne<AdminCounts>(`select
 (select count(*)::int from public.workshops) workshops,
 (select count(*)::int from public.workshops where status='active') "activeWorkshops",
 (select count(*)::int from public.subscriptions where status='trialing') trials,
 (select count(*)::int from public.subscriptions where status='active') "payingWorkshops",
 (select count(*)::int from public.subscriptions where status in('trialing','active','past_due') and current_period_end between current_date and current_date+7) "expiringSoon",
 (select count(*)::int from public.tickets where status<>'resolved') "openTickets",
 (select count(*)::int from public.platform_payments where status in('declared','provider_pending')) "pendingPayments"`))!;}
export async function getRevenueByCurrency():Promise<Money[]>{return(await sql<{currency:string;total:number}>("select currency,sum(amount)::int total from public.platform_payments where status='validated' group by currency order by currency")).map(r=>money(r.total,r.currency as CurrencyCode));}
export type WorkshopAdminRow={id:string;name:string;country_code:string;city:string|null;currency:string;status:string;created_at:string;owner_name:string;member_count:number;subscription_status:string|null;current_period_end:string|null};
export async function listWorkshops(search=""):Promise<WorkshopAdminRow[]>{return sql<WorkshopAdminRow>(`select w.id,w.name,w.country_code,w.city,w.currency,w.status::text,w.created_at,coalesce(u.full_name,'-') owner_name,count(m.id) filter(where m.status='active')::int member_count,s.status::text subscription_status,s.current_period_end from public.workshops w left join public.app_users u on u.id=w.owner_user_id left join public.memberships m on m.workshop_id=w.id left join public.subscriptions s on s.workshop_id=w.id where ($1='' or w.name ilike '%'||$1||'%') group by w.id,u.full_name,s.status,s.current_period_end order by w.created_at desc limit 200`,[search.trim()]);}
export type PlatformPaymentRow={id:string;workshop_id:string;workshop_name:string;subscription_id:string;plan_id:string|null;plan_label:string|null;plan_period_months:number|null;subscription_current_period_end:string|null;projected_period_start:string|null;projected_period_end:string|null;amount:number;currency:string;channel:string;external_reference:string|null;status:string;declared_at:string;review_note:string|null};
export async function listPlatformPayments(status?:string):Promise<PlatformPaymentRow[]>{const rows=await sql<PlatformPaymentRow>(`select pp.id,pp.workshop_id,w.name workshop_name,pp.subscription_id,coalesce(pp.plan_id,s.current_plan_id) plan_id,p.label plan_label,p.period_months plan_period_months,s.current_period_end subscription_current_period_end,pp.amount,pp.currency,pp.channel,pp.external_reference,pp.status::text,pp.declared_at,pp.review_note from public.platform_payments pp join public.workshops w on w.id=pp.workshop_id left join public.subscriptions s on s.id=pp.subscription_id left join public.plans p on p.id=coalesce(pp.plan_id,s.current_plan_id) where ($1::text is null or pp.status::text=$1) order by pp.declared_at desc limit 200`,[status??null]);return Promise.all(rows.map(async r=>{if(!r.plan_period_months)return{...r,projected_period_start:null,projected_period_end:null};const base=await nextPaymentPeriodStart(r.workshop_id,r.subscription_current_period_end);return{...r,projected_period_start:base,projected_period_end:addMonths(base,r.plan_period_months)};}));}
export async function validatePlatformPayment(params:{paymentId:string;reviewerUserId:string;note?:string|null}):Promise<{alreadyValidated:boolean;scheduledForLater?:boolean}>{return withPgTransaction(async client=>{const payment=await sqlOne<{id:string;workshop_id:string;subscription_id:string;plan_id:string|null;status:string}>("select id,workshop_id,subscription_id,plan_id,status::text from public.platform_payments where id=$1 for update",[params.paymentId],client);if(!payment)throw new Error("Reglement introuvable.");if(payment.status==="validated")return{alreadyValidated:true};const sub=await sqlOne<{id:string;current_plan_id:string;current_period_end:string|null}>("select id,current_plan_id,current_period_end from public.subscriptions where id=$1 for update",[payment.subscription_id],client);if(!sub)throw new Error("Abonnement introuvable.");const target=payment.plan_id??sub.current_plan_id,plan=await sqlOne<{period_months:number}>("select period_months from public.plans where id=$1",[target],client),today=todayIso(),start=await nextPaymentPeriodStart(payment.workshop_id,sub.current_period_end,client),end=addMonths(start,plan?.period_months??1),currentActive=Boolean(sub.current_period_end&&sub.current_period_end>today),update=!currentActive||sub.current_plan_id===target||start<=today;await sql("update public.platform_payments set status='validated',reviewed_at=now(),reviewed_by=$2,review_note=$3 where id=$1",[payment.id,params.reviewerUserId,params.note??null],client);await sql("insert into public.subscription_periods(id,subscription_id,workshop_id,plan_id,source_payment_id,period_start,period_end,status) values($1,$2,$3,$4,$5,$6,$7,$8)",[randomUUID(),sub.id,payment.workshop_id,target,payment.id,start,end,start<=today?"active":"scheduled"],client);if(update)await sql("update public.subscriptions set current_plan_id=$2,status='active',current_period_end=$3,grace_ends_at=null,row_version=row_version+1 where id=$1",[sub.id,target,end],client);await recordAudit({workshopId:payment.workshop_id,actorUserId:params.reviewerUserId,action:"platform_payment.validate",entityKind:"platform_payment",entityId:payment.id,reason:params.note??null,before:{planId:sub.current_plan_id,subscriptionEnd:sub.current_period_end},after:{planId:update?target:sub.current_plan_id,subscriptionEnd:update?end:sub.current_period_end,scheduledPlanId:target,accessPeriodStart:start,accessPeriodEnd:end}},client);return{alreadyValidated:false,scheduledForLater:!update};});}
export async function rejectPlatformPayment(params:{paymentId:string;reviewerUserId:string;note:string}):Promise<void>{await withPgTransaction(async client=>{const p=await sqlOne<{workshop_id:string}>("update public.platform_payments set status='rejected',reviewed_at=now(),reviewed_by=$2,review_note=$3 where id=$1 and status in('declared','provider_pending') returning workshop_id",[params.paymentId,params.reviewerUserId,params.note],client);if(p)await recordAudit({workshopId:p.workshop_id,actorUserId:params.reviewerUserId,action:"platform_payment.reject",entityKind:"platform_payment",entityId:params.paymentId,reason:params.note},client);});}
export type AuditRow={id:string;workshop_id:string|null;actor_name:string|null;action:string;entity_kind:string;entity_id:string|null;reason:string|null;created_at:string};
export async function listAudit(limit=100):Promise<AuditRow[]>{return sql<AuditRow>("select a.id,a.workshop_id,u.full_name actor_name,a.action,a.entity_kind,a.entity_id,a.reason,a.created_at from public.audit_log a left join public.app_users u on u.id=a.actor_user_id order by a.created_at desc limit $1",[limit]);}
export type TicketRow={id:string;workshop_id:string|null;workshop_name:string|null;requester_name:string|null;category:string;subject:string;status:string;created_at:string};
export async function listTickets(status?:string):Promise<TicketRow[]>{return sql<TicketRow>("select t.id,t.workshop_id,w.name workshop_name,t.requester_name,t.category,t.subject,t.status::text,t.created_at from public.tickets t left join public.workshops w on w.id=t.workshop_id where ($1::text is null or t.status::text=$1) order by t.created_at desc limit 200",[status??null]);}
export async function createTicket(params:{workshopId?:string|null;requesterUserId?:string|null;requesterName:string;requesterContact:string;category:string;subject:string;body:string}):Promise<string>{const id=randomUUID();await sql("insert into public.tickets(id,workshop_id,requester_user_id,requester_name,requester_contact,category,subject,body,status) values($1,$2,$3,$4,$5,$6,$7,$8,'open')",[id,params.workshopId??null,params.requesterUserId??null,params.requesterName,params.requesterContact,params.category,params.subject,params.body]);return id;}
async function nextPaymentPeriodStart(workshopId:string,currentEnd:string|null,e?:PgExecutor):Promise<string>{const row=await sqlOne<{period_end:string}>("select period_end from public.subscription_periods where workshop_id=$1 and status in('active','scheduled') order by period_end desc limit 1",[workshopId],e);return maxIsoDate(todayIso(),currentEnd,row?.period_end);}
function addMonths(start:string,months:number){const d=new Date(`${start}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+months);return d.toISOString().slice(0,10);}function maxIsoDate(...v:Array<string|null|undefined>){return v.filter((x):x is string=>Boolean(x)).sort().at(-1)??todayIso();}function todayIso(){return new Date().toISOString().slice(0,10);}
