import "server-only";
import {randomUUID} from "node:crypto";
import {recordAudit} from "@/lib/audit";
import {parseLimits,type PlanLimits,type PlanRow} from "@/lib/repos/contents";
import {getAffiliateProgramSettings} from "@/lib/repos/affiliates";
import {money,type CurrencyCode,type Money} from "@/lib/money";
import {sql,sqlOne,withPgTransaction,type PgExecutor} from "@/lib/supabase/postgres";
export type SubscriptionStatus="trial"|"active"|"renewal_due"|"suspended"|"cancelled";export type ManualPaymentChannel="mobile_money"|"airtel_money"|"transfer"|"cash";
export const MANUAL_PAYMENT_CHANNELS:ManualPaymentChannel[]=["mobile_money","airtel_money","transfer","cash"];
export const PAYMENT_CHANNEL_LABELS:Record<ManualPaymentChannel,string>={mobile_money:"MTN MoMo",airtel_money:"Airtel Money",transfer:"Virement",cash:"Especes"};
export type SubscriptionRow={id:string;workshop_id:string;plan_id:string;status:SubscriptionStatus;trial_ends_at:string|null;current_period_end:string|null;grace_ends_at:string|null;cancel_at_period_end:number;cancelled_at:string|null;created_at:string;updated_at:string};
export type PlatformPaymentStatus="declared"|"provider_pending"|"validated"|"rejected";export type SubscriptionPaymentProvider="manual"|"mtn_momo";
export type WorkshopPaymentRow={id:string;plan_id:string|null;plan_label:string|null;amount:number;currency:string;channel:string;provider:SubscriptionPaymentProvider;provider_status:string|null;provider_reference_id:string|null;external_reference:string|null;status:PlatformPaymentStatus;declared_at:string;reviewed_at:string|null;review_note:string|null};
export type AffiliatePaymentBenefit={eligible:boolean;discountRateBp:number;label:string|null};
export type PlanWithLimits=PlanRow&{limits:PlanLimits;price:Money;basePrice:Money;affiliateBenefit:AffiliatePaymentBenefit};export type SubscriptionUsage={activeMembers:number;memberLimit:number|null;remainingMembers:number|null;memberLimitReached:boolean;memberLimitExceeded:boolean};export type SubscriptionOverview={subscription:SubscriptionRow|null;currentPlan:PlanWithLimits|null;availablePlans:PlanWithLimits[];usage:SubscriptionUsage;payments:WorkshopPaymentRow[];affiliateBenefit:AffiliatePaymentBenefit};
export class SubscriptionError extends Error{constructor(message:string){super(message);this.name="SubscriptionError";}}
export async function getSubscriptionOverview(input:{workshopId:string;countryCode:string;currency:CurrencyCode}):Promise<SubscriptionOverview>{const [subscription,benefit,payments]=await Promise.all([getCurrentSubscription(input.workshopId),getAffiliatePaymentBenefit(input.workshopId),listWorkshopSubscriptionPayments(input.workshopId)]);const availablePlans=await listAvailablePlans(input.countryCode,input.currency,benefit);const currentPlan=subscription?availablePlans.find(p=>p.id===subscription.plan_id)??await getPlanWithLimits(subscription.plan_id,input.currency,benefit):null;return{subscription,currentPlan,availablePlans,usage:await getSubscriptionUsage(input.workshopId,currentPlan?.limits??null),payments,affiliateBenefit:benefit};}
async function paymentContext(workshopId:string,planId:string,currency:string,e:PgExecutor){const subscription=await sqlOne<{id:string}>("select id from public.subscriptions where workshop_id=$1 and status in('trialing','active','past_due') for update",[workshopId],e);if(!subscription)throw new SubscriptionError("Aucun abonnement actif ou en essai n'est associe a cet atelier.");const benefit=await getAffiliatePaymentBenefit(workshopId,e);const plan=await sqlOne<{id:string;currency:string;period_months:number;price_amount:number}>("select id,currency,period_months,price_amount from public.plans where id=$1 and status='active'",[planId],e);if(!plan)throw new SubscriptionError("Offre introuvable.");if(plan.currency!==currency)throw new SubscriptionError(`Devise incompatible : l'offre est en ${plan.currency}.`);const pending=await sqlOne("select id from public.platform_payments where workshop_id=$1 and plan_id=$2 and status in('declared','provider_pending')",[workshopId,planId],e);if(pending)throw new SubscriptionError("Un paiement est deja en attente de validation pour cette offre.");return{subscription,plan:{...plan,price:paymentPrice(Number(plan.price_amount),benefit)},benefit};}
export async function declareManualSubscriptionPayment(input:{workshopId:string;actorUserId:string;planId:string;amount:Money;channel:ManualPaymentChannel;externalReference:string;declaredAt:string;idempotencyKey:string;note?:string|null}):Promise<string>{if(input.amount.amount<=0)throw new SubscriptionError("Le montant paye doit etre positif.");if(!input.externalReference.trim())throw new SubscriptionError("La reference de paiement est obligatoire.");return withPgTransaction(async client=>{const existing=await sqlOne<{id:string}>("select id from public.platform_payments where idempotency_key=$1",[input.idempotencyKey],client);if(existing)return existing.id;const duplicate=await sqlOne("select id from public.platform_payments where workshop_id=$1 and external_reference=$2 and status<>'rejected'",[input.workshopId,input.externalReference.trim()],client);if(duplicate)throw new SubscriptionError("Cette reference a deja ete declaree.");const {subscription,plan,benefit}=await paymentContext(input.workshopId,input.planId,input.amount.currency,client);assertExpectedAmount(input.amount.amount,plan.price,benefit);const id=randomUUID();await sql(`insert into public.platform_payments(id,workshop_id,subscription_id,plan_id,amount,currency,channel,provider,external_reference,period_months,status,note,idempotency_key,declared_by,declared_at,raw_payload) values($1,$2,$3,$4,$5,$6,$7,'manual',$8,$9,'declared',$10,$11,$12,$13,$14::jsonb)`,[id,input.workshopId,subscription.id,plan.id,input.amount.amount,input.amount.currency,input.channel,input.externalReference.trim(),plan.period_months,input.note?.trim()||null,input.idempotencyKey,input.actorUserId,input.declaredAt,JSON.stringify({affiliate_discount_bp:benefit.eligible?benefit.discountRateBp:0})],client);await recordAudit({workshopId:input.workshopId,actorUserId:input.actorUserId,action:"platform_payment.declare",entityKind:"platform_payment",entityId:id,after:{planId:plan.id,amount:input.amount.amount,currency:input.amount.currency,channel:input.channel,affiliateDiscount:benefit.eligible}},client);return id;});}
export async function createProviderSubscriptionPayment(input:{workshopId:string;actorUserId:string;planId:string;amount:Money;provider:Exclude<SubscriptionPaymentProvider,"manual">;providerReferenceId:string;providerAmount:string;providerCurrency:string;externalId:string;payerPhoneE164:string;payerMsisdn:string;idempotencyKey:string}):Promise<{paymentId:string;providerReferenceId:string;externalId:string}>{return withPgTransaction(async client=>{const existing=await sqlOne<{id:string;provider_reference_id:string|null;provider_external_id:string|null}>("select id,provider_reference_id,provider_external_id from public.platform_payments where idempotency_key=$1",[input.idempotencyKey],client);if(existing)return{paymentId:existing.id,providerReferenceId:existing.provider_reference_id??input.providerReferenceId,externalId:existing.provider_external_id??input.externalId};const {subscription,plan,benefit}=await paymentContext(input.workshopId,input.planId,input.amount.currency,client);assertExpectedAmount(input.amount.amount,plan.price,benefit);const id=randomUUID(),raw={provider_status:"INITIATED",provider_amount:input.providerAmount,provider_currency:input.providerCurrency,payer_msisdn:input.payerMsisdn,affiliate_discount_bp:benefit.eligible?benefit.discountRateBp:0};await sql(`insert into public.platform_payments(id,workshop_id,subscription_id,plan_id,amount,currency,channel,provider,external_reference,provider_reference_id,provider_external_id,payer_phone_e164,period_months,status,idempotency_key,declared_by,raw_payload) values($1,$2,$3,$4,$5,$6,$7,$7,$8,$8,$9,$10,$11,'provider_pending',$12,$13,$14::jsonb)`,[id,input.workshopId,subscription.id,plan.id,input.amount.amount,input.amount.currency,input.provider,input.providerReferenceId,input.externalId,input.payerPhoneE164,plan.period_months,input.idempotencyKey,input.actorUserId,JSON.stringify(raw)],client);await recordAudit({workshopId:input.workshopId,actorUserId:input.actorUserId,action:"platform_payment.declare",entityKind:"platform_payment",entityId:id,after:{planId:plan.id,amount:input.amount.amount,currency:input.amount.currency,provider:input.provider,affiliateDiscount:benefit.eligible}},client);return{paymentId:id,providerReferenceId:input.providerReferenceId,externalId:input.externalId};});}
export async function markProviderPaymentRequested(input:{paymentId:string;workshopId:string;providerStatus:string}):Promise<void>{await sql("update public.platform_payments set raw_payload=raw_payload||$3::jsonb where id=$1 and workshop_id=$2 and status='provider_pending'",[input.paymentId,input.workshopId,JSON.stringify({provider_status:input.providerStatus,provider_checked_at:new Date().toISOString()})]);}
export async function markProviderPaymentFailed(input:{paymentId:string;workshopId:string;reason:string;providerStatus?:string;payload?:unknown}):Promise<void>{await sql("update public.platform_payments set status='rejected',reviewed_at=now(),review_note=$3,raw_payload=raw_payload||$4::jsonb where id=$1 and workshop_id=$2 and status='provider_pending'",[input.paymentId,input.workshopId,input.reason,JSON.stringify({provider_status:input.providerStatus??"FAILED",provider_checked_at:new Date().toISOString(),provider_payload:input.payload??null})]);}
export async function getProviderPaymentForCheck(input:{paymentId:string;workshopId:string;provider:Exclude<SubscriptionPaymentProvider,"manual">}):Promise<{id:string;provider_reference_id:string;status:PlatformPaymentStatus}|null>{return sqlOne("select id,provider_reference_id,status::text from public.platform_payments where id=$1 and workshop_id=$2 and provider=$3 and provider_reference_id is not null",[input.paymentId,input.workshopId,input.provider]);}
export async function recordProviderPaymentStatus(input:{paymentId:string;workshopId:string;providerStatus:string;payload:unknown}):Promise<void>{await sql("update public.platform_payments set raw_payload=raw_payload||$3::jsonb where id=$1 and workshop_id=$2",[input.paymentId,input.workshopId,JSON.stringify({provider_status:input.providerStatus,provider_checked_at:new Date().toISOString(),provider_payload:input.payload})]);}
const subSelect=`id,workshop_id,current_plan_id plan_id,case status when 'trialing' then 'trial' when 'past_due' then 'renewal_due' when 'expired' then 'suspended' else status::text end status,trial_ends_at,current_period_end,grace_ends_at,case when cancel_at_period_end then 1 else 0 end cancel_at_period_end,cancelled_at,created_at,updated_at`;
export async function getCurrentSubscription(workshopId:string,executor?:PgExecutor):Promise<SubscriptionRow|null>{const sub=await sqlOne<SubscriptionRow>(`select ${subSelect} from public.subscriptions where workshop_id=$1`,[workshopId],executor);if(!sub)return null;const period=await sqlOne<{plan_id:string;period_end:string}>("select plan_id,period_end from public.subscription_periods where workshop_id=$1 and status in('active','scheduled') and period_start<=current_date and period_end>current_date order by period_end desc limit 1",[workshopId],executor);return period?{...sub,plan_id:period.plan_id,status:"active",current_period_end:period.period_end}:sub;}
const planSelect="id,code,label,country_code,currency,price_amount,period_months,trial_days,limits_json::text,version,effective_from,archived_at";
async function listAvailablePlans(country:string,currency:CurrencyCode,benefit:AffiliatePaymentBenefit):Promise<PlanWithLimits[]>{const rows=await sql<PlanRow>(`select distinct on(code) ${planSelect} from public.plans where country_code=$1 and currency=$2 and status='active' order by code,version desc`,[country,currency]);return rows.sort((a,b)=>a.price_amount-b.price_amount).map(p=>withLimits(p,currency,benefit));}
async function getPlanWithLimits(id:string,currency:CurrencyCode,benefit:AffiliatePaymentBenefit):Promise<PlanWithLimits|null>{const p=await sqlOne<PlanRow>(`select ${planSelect} from public.plans where id=$1`,[id]);return p?withLimits(p,currency,benefit):null;}
async function getSubscriptionUsage(workshopId:string,limits:PlanLimits|null):Promise<SubscriptionUsage>{const r=await sqlOne<{n:number}>("select count(*)::int n from public.memberships where workshop_id=$1 and status='active'",[workshopId]),activeMembers=r?.n??0,memberLimit=limits?.members??null,remainingMembers=memberLimit===null?null:Math.max(memberLimit-activeMembers,0);return{activeMembers,memberLimit,remainingMembers,memberLimitReached:memberLimit!==null&&activeMembers>=memberLimit,memberLimitExceeded:memberLimit!==null&&activeMembers>memberLimit};}
async function listWorkshopSubscriptionPayments(workshopId:string):Promise<WorkshopPaymentRow[]>{return sql<WorkshopPaymentRow>(`select pp.id,pp.plan_id,p.label plan_label,pp.amount,pp.currency,pp.channel,pp.provider,pp.raw_payload->>'provider_status' provider_status,pp.provider_reference_id,pp.external_reference,pp.status::text,pp.declared_at,pp.reviewed_at,pp.review_note from public.platform_payments pp left join public.plans p on p.id=pp.plan_id where pp.workshop_id=$1 order by pp.declared_at desc limit 25`,[workshopId]);}
function withLimits(plan:PlanRow,currency:CurrencyCode,benefit:AffiliatePaymentBenefit):PlanWithLimits{const base=money(Number(plan.price_amount),currency);return{...plan,limits:parseLimits(plan.limits_json),basePrice:base,price:money(paymentPrice(base.amount,benefit),currency),affiliateBenefit:benefit};}

async function getAffiliatePaymentBenefit(workshopId:string,executor?:PgExecutor):Promise<AffiliatePaymentBenefit>{const row=await sqlOne<{attributed:boolean;validated_count:number}>(`select
    exists(select 1 from public.affiliate_attributions where workshop_id=$1) attributed,
    (select count(*)::int from public.platform_payments where workshop_id=$1 and status='validated') validated_count`,[workshopId],executor);
  const settings=await getAffiliateProgramSettings(executor);
  const discount=Math.max(0,Math.min(10000,settings.first_payment_discount_bp));
  const eligible=Boolean(row?.attributed)&&(row?.validated_count??0)===0&&discount>0;
  return{eligible,discountRateBp:discount,label:eligible?`Avantage code affilie : -${discount/100}% sur le premier paiement.`:null};}
function paymentPrice(baseAmount:number,benefit:AffiliatePaymentBenefit){return benefit.eligible?Math.max(0,Math.trunc(baseAmount*(10000-benefit.discountRateBp)/10000)):baseAmount;}
function assertExpectedAmount(amount:number,expected:number,benefit:AffiliatePaymentBenefit){if(amount!==expected)throw new SubscriptionError(benefit.eligible?`Montant invalide. Avec l'avantage affilie, le montant attendu est ${expected}.`:`Montant invalide. Le montant attendu est ${expected}.`);}
