import "server-only";
import {randomUUID} from "node:crypto";
import {recordAudit} from "@/lib/audit";
import {parseLimits} from "@/lib/repos/contents";
import type {WorkshopRole} from "@/lib/permissions";
import {sql,sqlOne,withPgTransaction,type PgExecutor} from "@/lib/supabase/postgres";
export type TeamStatus="active"|"disabled"|"invited";export type TeamFilter="all"|"active"|"money"|"disabled"|"owners";
export type TeamMemberRow={membership_id:string;user_id:string;full_name:string;phone_e164:string;email:string|null;role:WorkshopRole;can_view_money:boolean;status:TeamStatus;invited_at:string|null;created_at:string;assigned_items:number};
export type TeamStats={total:number;active:number;owners:number;moneyAccess:number;disabled:number;assignedItems:number};
export type TeamPlanUsage={planLabel:string|null;subscriptionStatus:string|null;memberLimit:number|null;activeMembers:number;remainingSlots:number|null;limitReached:boolean;limitExceeded:boolean};
export type TeamPage={members:TeamMemberRow[];stats:TeamStats;planUsage:TeamPlanUsage;total:number;page:number;pageSize:number;pageCount:number};
export class TeamError extends Error{constructor(message:string){super(message);this.name="TeamError";}}
export async function listTeamMembers(workshopId:string,options:{search?:string;filter?:TeamFilter;page?:number;pageSize?:number}={}):Promise<TeamPage>{const rows=(await sql<TeamMemberRow>(`select m.id membership_id,m.user_id,u.full_name,u.phone_e164,u.email,case when m.role='owner' then 'owner' else 'collaborator' end role,m.can_view_money,m.status::text,m.invited_at,m.created_at,count(i.id) filter(where i.status not in('delivered','cancelled'))::int assigned_items from public.memberships m join public.app_users u on u.id=m.user_id left join public.order_items i on i.workshop_id=m.workshop_id and i.assignee_user_id=m.user_id where m.workshop_id=$1 group by m.id,u.id order by case when m.role='owner' then 0 else 1 end,m.status,u.full_name`,[workshopId])).map(normaliseMember);const filtered=rows.filter(m=>matchesSearch(m,options.search??"")).filter(m=>matchesFilter(m,options.filter??"all"));const pageSize=Math.min(50,Math.max(1,Math.trunc(options.pageSize??10))),pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),page=Math.min(pageCount,Math.max(1,Math.trunc(options.page??1)));return{members:filtered.slice((page-1)*pageSize,page*pageSize),stats:buildStats(rows),planUsage:await getTeamPlanUsage(workshopId),total:filtered.length,page,pageSize,pageCount};}
export async function addExistingMember(input:{workshopId:string;actorUserId:string;phoneE164:string;role:WorkshopRole;canViewMoney:boolean}):Promise<void>{await withPgTransaction(async client=>{const usage=await getTeamPlanUsage(input.workshopId,client),user=await sqlOne<{id:string;full_name:string}>("select id,full_name from public.app_users where phone_e164=$1 and status='active'",[input.phoneE164],client);if(!user)throw new TeamError("Aucun compte actif ne correspond a ce numero.");const existing=await sqlOne<{id:string;status:string;role:string;can_view_money:boolean}>("select id,status,role,can_view_money from public.memberships where workshop_id=$1 and user_id=$2 for update",[input.workshopId,user.id],client);assertMemberLimitAllowsActivation(usage);const money=input.role==="owner"||input.canViewMoney;if(existing){if(existing.status==="active")throw new TeamError("Ce membre fait deja partie de l'atelier.");await sql("update public.memberships set role=$2,status='active',can_view_money=$3,joined_at=now(),row_version=row_version+1 where id=$1",[existing.id,input.role,money],client);await recordAudit({workshopId:input.workshopId,actorUserId:input.actorUserId,action:"member.permissions",entityKind:"membership",entityId:existing.id,before:existing,after:{status:"active",role:input.role,canViewMoney:money}},client);return;}const id=randomUUID();await sql("insert into public.memberships(id,workshop_id,user_id,role,can_view_money,status,invited_at,joined_at) values($1,$2,$3,$4,$5,'active',now(),now())",[id,input.workshopId,user.id,input.role,money],client);await recordAudit({workshopId:input.workshopId,actorUserId:input.actorUserId,action:"member.invite",entityKind:"membership",entityId:id,after:{userId:user.id,role:input.role,canViewMoney:money}},client);});}
export async function updateTeamMember(input:{workshopId:string;actorUserId:string;membershipId:string;role:WorkshopRole;status:TeamStatus;canViewMoney:boolean}):Promise<void>{await withPgTransaction(async client=>{const m=await sqlOne<{id:string;user_id:string;role:string;status:string;can_view_money:boolean}>("select id,user_id,role,status,can_view_money from public.memberships where id=$1 and workshop_id=$2 for update",[input.membershipId,input.workshopId],client);if(!m)throw new TeamError("Membre introuvable dans cet atelier.");if(m.user_id===input.actorUserId&&(input.status!=="active"||input.role!=="owner"))throw new TeamError("Vous ne pouvez pas retirer votre propre acces responsable.");const owners=await ownerCount(input.workshopId,client);if(m.role==="owner"&&(input.role!=="owner"||input.status!=="active")&&owners<=1)throw new TeamError("L'atelier doit conserver au moins un responsable actif.");if(m.status!=="active"&&input.status==="active")assertMemberLimitAllowsActivation(await getTeamPlanUsage(input.workshopId,client));const money=input.role==="owner"||input.canViewMoney;await sql("update public.memberships set role=$3,status=$4,can_view_money=$5,row_version=row_version+1 where id=$1 and workshop_id=$2",[input.membershipId,input.workshopId,input.role,input.status,money],client);await recordAudit({workshopId:input.workshopId,actorUserId:input.actorUserId,action:input.status==="disabled"?"member.disable":"member.permissions",entityKind:"membership",entityId:input.membershipId,before:m,after:{role:input.role,status:input.status,canViewMoney:money}},client);});}
export async function toggleTeamMemberStatus(input:{workshopId:string;actorUserId:string;membershipId:string;active:boolean}):Promise<void>{const m=await sqlOne<{role:"owner"|"collaborator";can_view_money:boolean;status:TeamStatus}>("select role,can_view_money,status from public.memberships where id=$1 and workshop_id=$2",[input.membershipId,input.workshopId]);if(!m)throw new TeamError("Membre introuvable.");await updateTeamMember({...input,role:m.role,status:input.active?"active":"disabled",canViewMoney:input.active&&m.can_view_money});}
export async function removeTeamMember(input:{workshopId:string;actorUserId:string;membershipId:string}):Promise<void>{return toggleTeamMemberStatus({...input,active:false});}
function normaliseMember(m:TeamMemberRow):TeamMemberRow{return{...m,role:m.role==="owner"?"owner":"collaborator",status:["active","disabled","invited"].includes(m.status)?m.status:"disabled",can_view_money:Boolean(m.can_view_money),assigned_items:Number(m.assigned_items??0)};}
function matchesSearch(m:TeamMemberRow,s:string){const t=s.trim().toLowerCase();return!t||`${m.full_name} ${m.phone_e164} ${m.email??""}`.toLowerCase().includes(t);}function matchesFilter(m:TeamMemberRow,f:TeamFilter){if(f==="active")return m.status==="active";if(f==="money")return m.can_view_money;if(f==="disabled")return m.status==="disabled";if(f==="owners")return m.role==="owner";return true;}
function buildStats(ms:TeamMemberRow[]):TeamStats{return ms.reduce<TeamStats>((s,m)=>{s.total++;s.active+=m.status==="active"?1:0;s.owners+=m.role==="owner"?1:0;s.moneyAccess+=m.can_view_money?1:0;s.disabled+=m.status==="disabled"?1:0;s.assignedItems+=m.assigned_items;return s;},{total:0,active:0,owners:0,moneyAccess:0,disabled:0,assignedItems:0});}
async function ownerCount(w:string,e:PgExecutor){const r=await sqlOne<{n:number}>("select count(*)::int n from public.memberships where workshop_id=$1 and role='owner' and status='active'",[w],e);return r?.n??0;}
export async function getTeamPlanUsage(workshopId:string,executor?:PgExecutor):Promise<TeamPlanUsage>{const row=await sqlOne<{active_members:number;label:string|null;status:string|null;limits_json:string|null}>(`select count(m.id) filter(where m.status='active')::int active_members,p.label,s.status::text,p.limits_json::text from public.workshops w left join public.memberships m on m.workshop_id=w.id left join public.subscriptions s on s.workshop_id=w.id left join public.plans p on p.id=s.current_plan_id where w.id=$1 group by p.label,s.status,p.limits_json`,[workshopId],executor);const activeMembers=row?.active_members??0,memberLimit=row?.limits_json?parseLimits(row.limits_json).members:null,remainingSlots=memberLimit===null?null:Math.max(memberLimit-activeMembers,0);return{planLabel:row?.label??null,subscriptionStatus:row?.status??null,memberLimit,activeMembers,remainingSlots,limitReached:memberLimit!==null&&activeMembers>=memberLimit,limitExceeded:memberLimit!==null&&activeMembers>memberLimit};}
function assertMemberLimitAllowsActivation(u:TeamPlanUsage){if(u.memberLimit!==null&&u.activeMembers>=u.memberLimit)throw new TeamError(`Limite d'abonnement atteinte : ${u.activeMembers}/${u.memberLimit} membres actifs.`);}
